#pragma kernel CSMain

Texture2D<float4> _InputTexture;
RWTexture2D<float4> _DenoisedOutput;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    float3 result = 0;

    for (int x = -1; x <= 1; x++)
    {
        for (int y = -1; y <= 1; y++)
        {
            result += _InputTexture[id.xy + int2(x, y)].rgb;
        }
    }

    _DenoisedOutput[id.xy] = float4(result / 9.0, 1.0);
}